language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t toko7/docker-react -f Dockerfile.dev .

script:
  - docker run toko7/docker-react npm run test -- --coverage
